// Auto-generated by Table.py

#pragma once

#include <cstdint>

static const unsigned LOG2_TABLE_DX7_ROM_1_SIZE = 12;
static const unsigned TABLE_DX7_ROM_1_SIZE      = 1 << LOG2_TABLE_DX7_ROM_1_SIZE;
static const unsigned TABLE_DX7_ROM_1_MASK      = TABLE_DX7_ROM_1_SIZE - 1;

extern const uint8_t table_dx7_rom_1[TABLE_DX7_ROM_1_SIZE];
